project:
  type: website

website:
  title: "alex hayes"
  site-url: https://www.alexpghayes.com/
  repo-url: https://github.com/alexpghayes/quarto-blog
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@alexpghayes"
    card-style: summary_large_image
  navbar:
    right:
      - text: about
        file: index.qmd
      - posts.qmd
      - papers/index.qmd
      - code/index.qmd
      - courses/index.qmd
      - talks/index.qmd
      - icon: github
        href: https://github.com/alexpghayes
      - icon: twitter
        href: https://twitter.com/alexpghayes

format:
  html:
    theme: ember.scss
    css: styles.css