---
title: "Resume"
subtitle: "Data scientist & Statistician"
---

This resume is [available as a pdf](resume\McMillan_Josiah_Resume_2024.pdf).

<!-- Statistician with 6 years of experience analyzing network data, performing causal inference and building tools for data scientists. Track record of strategic thinking, clear communication and successful remote work. -->

Statistician with 1 year of Data Analyst Experience working with marketing data to create new tools for canvassing managers, forecast future sales and marketing budget needs, and conduct analyses to optimize sales with a given budget. I have communicated both technical details to non-technical stakeholders and negotiated contracts from both the buy side with lead vendors and the sell side with homeowners looking to protect their largest investment. My work has allowed me to be engaged in forecasting and optimization of marketing budgets and the education I gained at KU Leuven has increased my statistical *techne*.


## Work Experience


:::: {.columns}
::: {.column width="90%" style="align: left;"}
##### **DaBella**
###### Marketing Data Analyst
:::
::: {.column width="10%" style="text-align: right;"}
**July 2019 - August 2020**   
:::
::::

- Reduced excess spend by an estimated $250,000 annually by on-boarding new software vendors to provide TCPA compliance and screen out duplicate prospects
- Optimized canvasser deployment increasing leads by 5% using cluster analysis and predictive modeling
- Ran and A/B tested email campaigns to previous customers using Mailchimp and Zapier, leading to 10% increase in customer referrals
- Provided up to date reporting on the performance of the marketing funnel
- Conducted meetings with lead vendors to target specific zipcodes and product classes using prior analysis to optimize sales given our marketing budget 
- Constructed marketing budget proposals given new branch openings, product mixes, historical sales, and ramp up factors 
- Sought out and partnered with new lead vendors, negotiated pricing, and monitored sales attributable to these vendors

:::: {.columns}
::: {.column width="70%" style="align: left;"}
##### **1st Security Bank**
###### Finance Intern
:::
::: {.column width="30%" style="text-align: right;"}
**Summer 2018**  
:::
::::

- Migrated financial data from balance sheet from excel sheets over to new platform for more accessible data formatting
- Created a forecast of key figures over the next three years based on past performance data and branch opening schedule using a heuristic model     

:::: {.columns}
::: {.column width="70%" style="align: left;"}
##### **DaBella**
###### Sales Representative
:::
::: {.column width="30%" style="text-align: right;"}
**Summer 2017**  
:::
::::

- Demonstrated a **30% closing rate** on sales presentations, showing strong technical communication skills and the ability to build trust and value with stakeholders.
- Sold new roofs to customers with a total one-month best of over **$100,000** of product sold
- Helped customers to complete financing applications for contracts averaging **$21,500** each, communicating financing details and important facts to non-technical stakeholders.
- Assisted customers in successfully navigating financing applications for contracts averaging, effectively translating loan application requirements to homeowners.


## Education  

:::: {.columns}
::: {.column width="90%" style="align: left;"}
##### **Katholieke Universiteit of Leuven (KU Leuven)**
###### MSc Statistics   
:::
::: {.column width="10%" style="text-align: right;"}
**Fall 2023**
:::
::::

:::: {.columns}
::: {.column width="90%" style="align: left;"}
##### **University of Washington, Seattle**
###### B.S. Economics
:::
::: {.column width="10%" style="text-align: right;"}
**2019**  
:::
::::

## Skills

- Network analysis, embeddings, clustering, data simulation, and NLP
- Data analysis, visualization, modeling, regression, generalized linear models, hypothesis testing
- Proficient in R, Python, tidyverse, git, SQL. Familiarity with AWS, Stan 
